apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: httproutes.cdn.kloudstack.ir
spec:
    group: cdn.kloudstack.ir
    versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              gateway:
                                  type: object
                                  properties:
                                      name:
                                          type: string
                              upstreamName:
                                  type: string
                              lbMethod:
                                  type: string
                                  enum: [ip_hash]
                                  default: "ip_hash"
                              path:
                                  type: object
                                  properties:
                                      type:
                                          type: string
                                          enum: [exact, prefix]
                                          default: "prefix"
                                      path:
                                          type: string
                                          default: "/"
                              cache:
                                  type: object
                                  properties:
                                      level:
                                          type: string
                                          enum:
                                              [
                                                  bypass,
                                                  standard,
                                                  ignore-query-string,
                                              ]
                                          default: "bypass"
                                      ignoreUpstreamCacheSettings:
                                          type: boolean
                                          default: false
                                      browserTTL:
                                          type: integer
                                          default: 3600
                                      edgeTTL:
                                          type: integer
                                          default: 3600
                                      nonSuccessTTL:
                                          type: integer
                                          default: 0
                                      staleTTL:
                                          type: integer
                                          default: 0
                                      immutable:
                                          type: boolean
                                          default: false
                      status:
                          description: |-
                              Most recently observed status of the httproute. This data may not be up
                              to date. Populated by the system. Read-only.
                          properties:
                              redisKey:
                                  description: The stored redis key
                                  type: string
                          type: object
          selectableFields:
              - jsonPath: .spec.gateway.name
          additionalPrinterColumns:
              - name: Gateway
                type: string
                description: agteway
                jsonPath: .spec.gateway.name
                priority: 0
              - name: UpstreamName
                type: string
                description: Current Upstream name
                jsonPath: .spec.upstreamName
                priority: 0
              - name: PathType
                type: string
                description: path type
                jsonPath: .spec.path.type
                priority: 0
              - name: Path
                type: string
                description: path
                jsonPath: .spec.path.path
                priority: 0
              - name: Age
                type: date
                jsonPath: .metadata.creationTimestamp
          subresources:
              status: {}
    scope: Namespaced
    names:
        plural: httproutes
        singular: httproute
        kind: HTTPRoute
        shortNames:
            - hr
