apiVersion: v1
kind: ServiceAccount
metadata:
    name: gatekeeper
    namespace: kloudstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: kloudstack:gatekeeper
rules:
    - apiGroups:
          - "*"
      resources:
          - "*"
      verbs:
          - "*"
    - nonResourceURLs:
          - "*"
      verbs:
          - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kloudstack:gatekeeper
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kloudstack:gatekeeper
subjects:
    - kind: ServiceAccount
      name: gatekeeper
      namespace: kloudstack
