apiVersion: v1
kind: ServiceAccount
metadata:
    name: kloudstack-gatekeeper
    namespace: hicompute
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: hicompute:kloudstack:gatekeeper
rules:
    - apiGroups:
          - "*"
      resources:
          - "*"
      verbs:
          - "*"
    - nonResourceURLs:
          - "*"
      verbs:
          - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: hicompute:kloudstack:gatekeeper
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kloudstack:gatekeeper
subjects:
    - kind: ServiceAccount
      name: kloudstack-gatekeeper
      namespace: hicompute
