apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: dhcp-server
    namespace: kloudstack
    labels:
        k8s-app: dhcp-server
spec:
    selector:
        matchLabels:
            k8s-app: dhcp-server
    template:
        metadata:
            labels:
                k8s-app: dhcp-server
        spec:
            serviceAccountName: dhcp-server
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/control-plane
                                    operator: Exists
            hostNetwork: true
            containers:
                - name: dhcp-server
                  image: registry.ik8s.ir/hicompute/kloudstack:v0.0.0-alpha.0
                  imagePullPolicy: Always
                  args:
                      - "dhcpd"
                      - "--server=192.168.1.1"
                  resources:
                      requests:
                          memory: "32Mi"
                          cpu: "100m"
                      limits:
                          memory: "128Mi"
                          cpu: "200m"
            tolerations:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
                  effect: NoSchedule
