apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    labels:
        k8s-app: metric-exporter
        release: prom
    name: metric-exporter
    namespace: kloudstack
spec:
    endpoints:
        - honorLabels: true
          interval: 30s
          path: /metrics
          port: metrics
          scheme: http
    namespaceSelector:
        matchNames:
            - kloudstack
    selector:
        matchLabels:
            k8s-app: metric-exporter
