apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        k8s-app: ovn-central
    name: ovn-central
    namespace: kloudstack
spec:
    serviceName: ovn-central
    replicas: 3
    selector:
        matchLabels:
            k8s-app: ovn-central
    template:
        metadata:
            labels:
                k8s-app: ovn-central
                name: ovn-central
        spec:
            containers:
                - name: nb-ovsdb
                  args:
                      - -c
                      - |
                          set -e
                          CLUSTER_CMD_OPTIONS=--db-nb-cluster-local-addr=${POD_IP}
                          if [ "$POD_IP" != "$CENTRAL_CLUSTER_LEADER_IP" ]; then
                              CLUSTER_CMD_OPTIONS="${CLUSTER_CMD_OPTIONS} --db-nb-cluster-remote-addr=${CENTRAL_CLUSTER_LEADER_IP}"
                          fi

                          ovn-ctl run_nb_ovsdb \
                            ${CLUSTER_CMD_OPTIONS} \
                            --db-nb-addr=${POD_IP} \
                            --db-nb-create-insecure-remote=yes
                  command:
                      - sh
                  env:
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: CENTRAL_CLUSTER_LEADER_IP
                        value: "192.168.12.177"
                  image: registry.ik8s.ir/hicompute/ovs:dpdk
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 6641
                        protocol: TCP
                      - containerPort: 6643
                        protocol: TCP
                  resources: {}
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                              - SYS_MODULE
                              - SYS_NICE
                              - NET_BIND_SERVICE
                      privileged: true
                  volumeMounts:
                      - mountPath: /var/run/ovn
                        name: ovnrun
                      - mountPath: /var/lib/ovn
                        name: ovnlib
                      - mountPath: /var/log/ovn
                        name: log
                - name: sb-ovsdb
                  args:
                      - -c
                      - |
                          set -e
                          CLUSTER_CMD_OPTIONS=--db-sb-cluster-local-addr=${POD_IP}
                          if [ "$POD_IP" != "$CENTRAL_CLUSTER_LEADER_IP" ]; then
                              CLUSTER_CMD_OPTIONS="${CLUSTER_CMD_OPTIONS} --db-sb-cluster-remote-addr=${CENTRAL_CLUSTER_LEADER_IP}"
                          fi

                          ovn-ctl run_sb_ovsdb \
                            ${CLUSTER_CMD_OPTIONS} \
                            --db-sb-addr=${POD_IP} \
                            --db-sb-create-insecure-remote=yes
                  command:
                      - sh
                  env:
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: CENTRAL_CLUSTER_LEADER_IP
                        value: "192.168.12.177"
                  image: registry.ik8s.ir/hicompute/ovs:dpdk
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 6642
                        protocol: TCP
                      - containerPort: 6644
                        protocol: TCP
                  resources: {}
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                              - SYS_MODULE
                              - SYS_NICE
                              - NET_BIND_SERVICE
                      privileged: true
                  volumeMounts:
                      - mountPath: /var/run/ovn
                        name: ovnrun
                      - mountPath: /var/lib/ovn
                        name: ovnlib
                      - mountPath: /var/log/ovn
                        name: log

                - name: northd
                  args:
                      - --ovn-northd-nb-db=tcp:ovn-central-0.ovn-central:6641
                      - --ovn-northd-sb-db=tcp:ovn-central-0.ovn-central:6642
                  command:
                      - ovn-northd
                  image: registry.ik8s.ir/hicompute/ovs:dpdk
                  imagePullPolicy: IfNotPresent
                  resources: {}
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                              - SYS_MODULE
                              - SYS_NICE
                              - NET_BIND_SERVICE
                      privileged: true
                  volumeMounts:
                      - mountPath: /var/run/ovn
                        name: ovnrun
                      - mountPath: /var/lib/ovn
                        name: ovnlib
                      - mountPath: /var/log/ovn
                        name: log
            dnsPolicy: ClusterFirstWithHostNet
            hostIPC: true
            hostNetwork: true
            hostPID: true
            imagePullSecrets:
                - name: regcred
            nodeSelector:
                node-role.kubernetes.io/control-plane: "true"
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                              matchLabels:
                                  k8s-app: ovn-central
                          topologyKey: kubernetes.io/hostname
            volumes:
                - hostPath:
                      path: /var/run/ovn
                      type: DirectoryOrCreate
                  name: ovnrun
                - hostPath:
                      path: /var/lib/ovn
                      type: DirectoryOrCreate
                  name: ovnlib
                - hostPath:
                      path: /var/log/ovn
                      type: DirectoryOrCreate
                  name: log
---
apiVersion: v1
kind: Service
metadata:
    name: ovn-central
    namespace: kloudstack
spec:
    clusterIP: None
    ipFamilies:
        - IPv4
    selector:
        k8s-app: ovn-central
