apiVersion: v1
kind: ServiceAccount
metadata:
    name: kloudstack-compute-controller
    namespace: hicompute
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: hicompute:kloudstack:compute-controller
rules:
    - apiGroups:
          - ""
      resources:
          - "secrets"
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - ipam.kloudstack.ir
      resources:
          - "clusterips"
          - "clusterippools"
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - ipam.kloudstack.ir
      resources:
          - clusterips/status
          - clusterippools/status
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
    - apiGroups:
          - "kubevirt.io"
      resources:
          - virtualmachines
          - virtualmachineinstances
      verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: hicompute:kloudstack:compute-controller
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: hicompute:kloudstack:compute-controller
subjects:
    - kind: ServiceAccount
      name: kloudstack-compute-controller
      namespace: hicompute
